# Generated by Django 4.0.1 on 2022-01-24 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentHouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='houses/')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('billed', models.CharField(choices=[('monthly', 'monthly'), ('quaterly', 'quaterly'), ('yearly', 'yearly')], default='yearly', max_length=15)),
                ('display', models.BooleanField(default=True)),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentHouse.housetype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentHouse.region')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='rentHouse.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentHouse.state'),
        ),
    ]
