# Generated by Django 4.0.1 on 2022-01-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentHouse', '0002_housetype_region_state_uploadhouse_region_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
