# Generated by Django 4.0.1 on 2022-01-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentHouse', '0003_alter_housetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
