# Generated by Django 4.0.1 on 2022-01-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentHouse', '0004_alter_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhouse',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
