# Generated by Django 4.0.1 on 2022-02-10 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentHouse', '0005_uploadhouse_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhouse',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
