# Generated by Django 4.0.1 on 2022-02-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentHouse', '0006_uploadhouse_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_photo', models.ImageField(upload_to='more_photos/')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='uploadhouse',
            name='more_photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentHouse.house_photos'),
        ),
    ]
